name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #java: [ 1.6, 6.0.83, 7, 7.0.181, 8, 8.0.192, 9.0,x, 10, 11.0.x, 11.0.3, 12, 13 ]
        java: [ 8, 8.0.192, 9.0,x, 10, 11.0.x, 11.0.3, 12, 13 ]
        #java: [ 8, 10, 11, 12, 13 ]

    name: Java ${{ matrix.java }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build with Maven
        env:
          JAVA_VERSION: ${{ matrix.java }}
          gitlabToken: ${{ secrets.gitlabToken }}
        run: mvn --file pom.xml --settings settings.xml compile

      - name: Test with Maven
        env:
          JAVA_VERSION: ${{ matrix.java }}
        run: mvn --file pom.xml test
